#include "gme12864.h"
#include "stm32f4xx_hal.h"
#include <string.h>  // memcpy, memset

/* I2C handle generated by CubeMX */
extern I2C_HandleTypeDef hi2c1;

/* Screen buffer */
static uint8_t OLED_Buffer[OLED_WIDTH * OLED_HEIGHT / 8];

/* Write command to OLED */
void OLED_WriteCommand(uint8_t cmd)
{
    uint8_t data[2];
    data[0] = 0x00; // Command prefix
    data[1] = cmd;
    HAL_I2C_Master_Transmit(&hi2c1, OLED_ADDR, data, 2, HAL_MAX_DELAY);
}

/* Write data to OLED */
void OLED_WriteData(uint8_t *buffer, uint16_t buff_size)
{
    uint8_t data[buff_size + 1];
    data[0] = 0x40; // Data prefix
    memcpy(&data[1], buffer, buff_size);
    HAL_I2C_Master_Transmit(&hi2c1, OLED_ADDR, data, buff_size + 1, HAL_MAX_DELAY);
}

/* Clear buffer */
void OLED_Clear(void)
{
    memset(OLED_Buffer, 0, sizeof(OLED_Buffer));
}

/* Update screen with buffer */
void OLED_UpdateScreen(void)
{
    for (uint8_t page = 0; page < 8; page++)
    {
        OLED_WriteCommand(0xB0 + page);     // Set page
        OLED_WriteCommand(0x00);            // Set lower column
        OLED_WriteCommand(0x10);            // Set higher column
        OLED_WriteData(&OLED_Buffer[OLED_WIDTH * page], OLED_WIDTH);
    }
}

/* Draw a single pixel into buffer */
void OLED_DrawPixel(uint8_t x, uint8_t y, uint8_t color)
{
    if (x >= OLED_WIDTH || y >= OLED_HEIGHT)
        return;

    if (color)
        OLED_Buffer[x + (y / 8) * OLED_WIDTH] |= 1 << (y % 8);
    else
        OLED_Buffer[x + (y / 8) * OLED_WIDTH] &= ~(1 << (y % 8));
}

/* Draw 16x16 bitmap */
void OLED_DrawBitmap(uint8_t x, uint8_t y, const uint8_t bitmap[16][16])
{
    for (uint8_t row = 0; row < 16; row++)
    {
        for (uint8_t col = 0; col < 16; col++)
        {
            OLED_DrawPixel(x + col, y + row, bitmap[row][col] ? 1 : 0);
        }
    }
}

/* Initialize OLED */
void OLED_Init(void)
{
    HAL_Delay(100);  // Wait for OLED to power up

    /* Initialization sequence (example for GME12864) */
    OLED_WriteCommand(0xAE); // Display off
    OLED_WriteCommand(0xA6); // Normal display
    OLED_WriteCommand(0xA8); // Set multiplex ratio
    OLED_WriteCommand(0x3F);
    OLED_WriteCommand(0xD3); // Set display offset
    OLED_WriteCommand(0x00);
    OLED_WriteCommand(0x40); // Set start line
    OLED_WriteCommand(0x8D); // Charge pump
    OLED_WriteCommand(0x14);
    OLED_WriteCommand(0x20); // Memory addressing mode
    OLED_WriteCommand(0x00);
    OLED_WriteCommand(0xAF); // Display on

    OLED_Clear();
    OLED_UpdateScreen();
}
